# Generated by Django 4.1 on 2023-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='background_images/bg1.jpg', upload_to='background_images/', verbose_name='صورة الخلفية')),
            ],
            options={
                'verbose_name': 'صورة الخلفية',
                'verbose_name_plural': 'صور الخلفية',
            },
        ),
    ]
