# Generated by Django 4.1 on 2023-08-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان المنشور')),
                ('subtitle', models.CharField(max_length=64, verbose_name='العنوان الفرعي')),
                ('body', models.TextField(verbose_name='محتوى المنشور')),
                ('post_image', models.ImageField(upload_to='post_images/', verbose_name='صورة المنشور')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='التصنيف')),
            ],
        ),
    ]
