# Generated by Django 4.1 on 2023-08-08 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'منشور', 'verbose_name_plural': 'المنشورات'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
