# Generated by Django 4.1 on 2023-08-09 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blogpost_options_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ إضافة المنشور'),
        ),
    ]
