# Generated by Django 3.2.6 on 2023-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
